#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

echo "br_netfilter" >> /etc/modules

echo "
net.ipv4.ip_forward=1
net.bridge.bridge-nf-call-iptables=0
" >> /etc/sysctl.d/60-mcp-underlay.conf
